webtalk_init -webtalk_dir /home/deanzhou/Desktop/Stanford/Junior/Fall/EE 108/Labs/lab0/lab0.sim/sim_1/behav/xsim/xsim.dir/lab0_top_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Sep 23 15:34:40 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7e75c728-55e5-48a3-b940-b6207f51ed95" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "178e50447b5e4eadb3885d997ae73e1e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 21.04" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 4800H with Radeon Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1400.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "25 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.19_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "116072_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2411593854 -regid "" -xml /home/deanzhou/Desktop/Stanford/Junior/Fall/EE 108/Labs/lab0/lab0.sim/sim_1/behav/xsim/xsim.dir/lab0_top_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/deanzhou/Desktop/Stanford/Junior/Fall/EE 108/Labs/lab0/lab0.sim/sim_1/behav/xsim/xsim.dir/lab0_top_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/deanzhou/Desktop/Stanford/Junior/Fall/EE 108/Labs/lab0/lab0.sim/sim_1/behav/xsim/xsim.dir/lab0_top_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
